// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xidbqqozwknlcpcnfhfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpZGJxcW96d2tubGNwY25maGZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NTg2ODgsImV4cCI6MjA2NTQzNDY4OH0.ZFbtBABA278cW2tO5wU7s_VxlQfq7XHA6xGqve26jHA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);